name: Verify
on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:

permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  lychee:
    name: Lychee
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          fail: ${{ github.ref != 'refs/heads/master' }}
          failIfEmpty: false
          jobSummary: true
          format: markdown
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        node-version:
          - 20
          - 22
          - 24
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Node.js setup
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm test
